### ISSUE TITLE
Cannot find module 'babel-runtime' during build (fix)

### ISSUE THREAD

**Issue by abruere** [learningequality/vue-intl#13]
Thanks for this repo providing ICU message format syntax in Vue.

I am working on a [potential](https://github.com/learningequality/vue-intl/issues/14) PR but encountered this error during build, using node v8.4:

```sh
> NODE_ENV=development babel-node build

resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.requireRelative.resolve (/home/andy/git/vue-intl/node_modules/require-relative/index.js:30:17)
    at resolve (/home/andy/git/vue-intl/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/home/andy/git/vue-intl/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /home/andy/git/vue-intl/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (<anonymous>)
    at loadPreset (/home/andy/git/vue-intl/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/home/andy/git/vue-intl/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/home/andy/git/vue-intl/node_modules/babel-preset-es2015-rollup/index.js:3:18)
```

According to the stack and this [related issue](https://github.com/rollup/babel-preset-es2015-rollup/issues/18), this can be fixed by updating babel-preset-es2015-rollup to [v3](https://github.com/rollup/babel-preset-es2015-rollup/blob/master/CHANGELOG.md), that address this specifically.

I tried locally and the error was fixed. Maybe I should open a PR?

**Comment by abruere** [comment]
Closing this as dependencies have been updated since then.
