### ISSUE TITLE
`Intl` dependency may be missing?

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/vue-intl#2]
When trying to use the package, I get this error from Karma:

```
  ReferenceError: Can't find variable: Intl
  at /Users/d/Projects/learning_equality/repos/kolibri/kolibri/core/assets/test/core_app_mediator.js:25488 <- webpack:///~/vue-intl/dist/vue-intl.js:2582:0
```

It looks like maybe `state.js` is referencing `Intl.DateTimeFormat` and `Intl.NumberFormat` without importing `Intl`?

---

As a side note: I tried to put together a PR but now I'm having trouble working on this project locally. I checked out the repo and ran:

``` bash
vue-intl> npm install
```

This failed in two ways. First try:

``` bash
> fsevents@1.0.12 install /Users/d/Projects/learning_equality/repos/vue-intl/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/d/Projects/learning_equality/repos/vue-intl/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" is installed via remote

> vue-intl@0.3.0 prepublish /Users/d/Projects/learning_equality/repos/vue-intl
> npm run clean && npm run build


> vue-intl@0.3.0 clean /Users/d/Projects/learning_equality/repos/vue-intl
> rimraf coverage/ dist/


> vue-intl@0.3.0 build /Users/d/Projects/learning_equality/repos/vue-intl
> npm run build:dev && npm run build:prod


> vue-intl@0.3.0 build:dev /Users/d/Projects/learning_equality/repos/vue-intl
> NODE_ENV=development babel-node build

/Users/d/Projects/learning_equality/repos/vue-intl/node_modules/core-js/modules/es6.promise.js:125
    if(abrupt)throw abrupt.error;
              ^

Error: Cannot find module 'intl' from '/Users/d/Projects/learning_equality/repos/vue-intl/src'
    at /Users/d/Projects/learning_equality/repos/vue-intl/node_modules/resolve/lib/async.js:46:17
    at process (/Users/d/Projects/learning_equality/repos/vue-intl/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/d/Projects/learning_equality/repos/vue-intl/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/d/Projects/learning_equality/repos/vue-intl/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/d/Projects/learning_equality/repos/vue-intl/node_modules/resolve/lib/async.js:92:31)
    at /Users/d/Projects/learning_equality/repos/vue-intl/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Second try:

``` bash
> vue-intl@0.3.0 prepublish /Users/d/Projects/learning_equality/repos/vue-intl
> npm run clean && npm run build


> vue-intl@0.3.0 clean /Users/d/Projects/learning_equality/repos/vue-intl
> rimraf coverage/ dist/


> vue-intl@0.3.0 build /Users/d/Projects/learning_equality/repos/vue-intl
> npm run build:dev && npm run build:prod


> vue-intl@0.3.0 build:dev /Users/d/Projects/learning_equality/repos/vue-intl
> NODE_ENV=development babel-node build

[BABEL] Note: The code generator has deoptimised the styling of "/Users/d/Projects/learning_equality/repos/vue-intl/node_modules/intl/locale-data/complete.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/Users/d/Projects/learning_equality/repos/vue-intl/node_modules/intl/lib/core.js" as it exceeds the max of "100KB".
```

And it hung there for like 20 minutes before I killed it.

**Comment by rtibbles** [comment]
I think the first issue is probably just a matter of getting Intl polyfilled right - formatjs docs have more info.

The second one is a little more troubling, odd that the build is hanging like that.

What node version were you using at the time?

**Comment by indirectlylit** [comment]
``` bash
> node --version
v5.6.0
```
